#Radioactive decay simulation
/control/verbose 0
/control/saveHistory
/run/verbose 0
#
# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 48
#

/CDEX/sim/set/mode CDEXBucket
/CDEX/src/type Bucket

# Initialize kernel
/run/initialize

/gps/particle gamma
/gps/energy 2.6 MeV
/run/beamOn 1000000

/gps/particle gamma
/gps/energy 1 MeV
/run/beamOn 1000000
